### ISSUE TITLE
Hook error: No DSL object found

### ISSUE THREAD

**Issue by szabgab** [ambs/Dancer2-Plugin-JWT#2]
This is the error I get in the browser:

```
Internal Server Error

Exception caught in 'core.app.after_request' filter: Hook error: No DSL object found at /home/vagrant/localperl/lib/site_perl/5.22.0/Dancer2/Plugin/JWT.pm line 17.
 at /home/vagrant/localperl/lib/site_perl/5.22.0/Dancer2/Core/App.pm line 973.
 at /home/vagrant/localperl/lib/site_perl/5.22.0/Dancer2/Core/Role/Hookable.pm line 114.
```

config.yml has

```
plugins:
  JWT:
    secret: "secret"
```

The module is

```
package Abc;
use Dancer2;
use Dancer2::Plugin::JWT;

our $VERSION = '0.1';

get '/' => sub {
        jwt { t  => 42 };
        return 'start';
};

true;
```

Dancer2 0.163000
Dancer2::Plugin::JWT 0.005

the same error with Dancer2 0.166001 which is currently the latest.

**Comment by shadowwa** [comment]
It worked for my only if I have only one plugin config ie:

```
plugins:
  JWT:
    secret: "secret"
```

as soon as I have another plugin configured:

```
plugins:
  JWT:
    secret: "secret"
  Database:
    connections:
    …
```

I got the same error.

To be able to use several plugins configuration, I had to use the previous version:
Dancer2::Plugin::JWT 0.004

**Comment by ambs** [comment]
I think this is still a problem on Dancer 2 Plugin system. AFAIK, the Dancer 2 Plugin System, version 2, should be out soon, and fix some of those issues.

@SysPete any hint menwhile?

**Comment by SysPete** [comment]
Started investigating this and found that my original plugin2 PR was against what must have been something around v0.002 and changes introduced in 0.003 broke plugin2 compat so I'm working on that first. PR should arrive very soon.

**Comment by ambs** [comment]
@shadowwa , @szabgab , can you please latest release? (0.006)

**Comment by shadowwa** [comment]
I got the same error (it maybe a different issue, I just saw that the exception in my case was in 'core.app.before_request')

```
Exception caught in 'core.app.before_request' filter: Hook error: No DSL object found at /home/shad/Work/iptrack/Iptrackrest/local/lib/perl5/Dancer2/Plugin/JWT.pm line 17.
 at /home/shad/Work/iptrack/Iptrackrest/local/lib/perl5/Dancer2/Core/App.pm line 971.
 at /home/shad/Work/iptrack/Iptrackrest/local/lib/perl5/Dancer2/Core/Role/Hookable.pm line 115.
```

**Comment by SysPete** [comment]
@ambs with plugin2 we can prevent these `No DSL object found` errors by making sure the app has the plugin loaded by using plugin2's `with_plugin` method. For existing D2 releases we need to just try to make sure we don't get into trouble.

I think the simplest way to solve this problem for now would be to add a singleton `$secret` which is assigned the value of `$config->{secret}` inside `on_plugin_import`. The problem with doing this is that the secret cannot be set via the `set` keyword after the plugin has been imported so if you want to `set` the secret inside the application itself then it will need to be done inside a `BEGIN` block. Since current docs state that the secret must be defined in `config.yml` I don't see this as a big issue.

I'm thinking along the lines of: https://github.com/SysPete/Dancer2-Plugin-JWT/commit/5862cb97407a115f53ff71ea1bc6fb802e432fa5

**Comment by shadowwa** [comment]
@SysPete that seems to do the trick, I don't have error anymore using your version

**Comment by ambs** [comment]
@SysPete, can you please make your branch a Pull Request? :-)
Thank you, once more.

**Comment by ambs** [comment]
Just merged @SysPete patch, and released to CPAN.
@shadowwa, can you please test with it? Should hit CPAN mirrors in some minutes.

Thanks @SysPete yet again :)

**Comment by shadowwa** [comment]
The 0.007 version works for me.

**Comment by ambs** [comment]
Great. Closing issue. Poke me again if needed.
